### ISSUE TITLE
Navigation bar shifts up after authenticating with Facebook 

### ISSUE THREAD

**Issue by adam-kwon** [romaonthego/RESideMenu#159]
Hi,

I am running into an odd issue.  After coming back from the Facebook's authentication page (the redirect to Safari where users authorize the app in Facebook), the navigation bar is shifted up on the screen.

I have created a sample project to demonstrate this issue.  It can be downloaded here.
https://www.dropbox.com/s/wjvt3thuacnijd8/residetest.zip

To reproduce:
1. Open menu 
2. Click on login (lower bottom)
3. Safari will open and Facebook's auth screen will show.  Authenticate.
4. After authenticating, will automatically go back to app
5. Close the menu
Note: To retest after the first time, you will have to uninstall the app after logging because FB token is cached.

It is a basic app using RESideMenu and a Facebook login.  The problem goes away if I hide the menu by calling hideMenuViewController (MenuViewController.m, line 53).

The problem also goes away if I reposition the navigation controller's view after the app becomes active again (after coming back from the Facebook authentication).  However, the 'y' value cannot be 0.  It needs to be a non zero value (like 0.00001).

This happens on both the simulator and the device.

Screenshot here:

<img src="http://i.imgur.com/qWxBhC7.png">

**Comment by anphanngocvn** [comment]
You said that you would suggest not hiding the status bar at all. Could you please explain more your suggestion? @romaonthego I am getting this issue on my app.

**Comment by anphanngocvn** [comment]
Steps for replication:
1. Open the side menu, on the side menu, I have a button. Press on that button will present another view controller.
2. Force app to background and then open the app again.
3. Close the side menu => the navigation bar is shifted up

<img width="141" alt="screen shot 2016-05-04 at 2 39 06 pm" src="https://cloud.githubusercontent.com/assets/16580103/15007830/02018fc2-1206-11e6-8156-c8e4448fe6e8.png">
