### ISSUE TITLE
Swift Port

### ISSUE THREAD

**Issue by SSA111** [romaonthego/RESideMenu#196]
Anybody interested in helping converting this fantastic iOS component to Swift? 
I have started converting the basic Objective-C to Swift in this branch: 
https://github.com/SSA111/RESideMenuSwift

**Comment by toocruel** [comment]
Ths is one convert of swfit .  https://github.com/toocruel/iosSideMenuSwift

**Comment by SSA111** [comment]
It is not converted to swift, just bridged from Obje-C.

**Comment by toocruel** [comment]
Oh, i made a fool!
