### ISSUE TITLE
Background image idea

### ISSUE THREAD

**Issue by matejkramny** [romaonthego/RESideMenu#225]
you know how passbook shows you a bit of the homescreen in its background?

I am doing a bit of research into this right now, so want to ask for your opinions and knowledge of this as I can't find anything on the internet.

**Comment by romaonthego** [comment]
I don't think it's possible. There was a private method in iOS7, but it was removed - https://gist.github.com/steventroughtonsmith/6763213

**Comment by matejkramny** [comment]
More information: http://stackoverflow.com/questions/18924135/ios-7-display-user-wallpaper-as-uiwindow-background
