### ISSUE TITLE
Menu appear totally white.

### ISSUE THREAD

**Issue by inso1337** [romaonthego/RESideMenu#237]
Hi,
I try RESideMenu for the first time today, so i pull the latest version and i compile the examples project.
I think the last version has a bug because when i touch the left or right button, the MenuView appear but totally white (same for the background, buttons and everything on the view).
I finally tried with an other fork of RESideMenu based on a old version everything work well (with the same dev/test environment , it's why i think you may have a little bug on the latest version.

**Comment by wdcurry** [comment]
sounds like your menu view has a white background. The text defaults to white, and thus you would see it as all white. Manually set the background color in viewDidLoad to see if that helps.

**Comment by edwardtoday** [comment]
I encountered the same issue.
RESideMenu used to work on iOS 8.4. I wanted to test my app on iOS 9 today. And the menu background image did not show up. Thus the background color, which was white in my code, is shown.
Something is wrong with the background image settings.

**Comment by canaksoy** [comment]
If you set a backgroundImage, don't forget to set the Menu View Controller's background color to clear color.

**Comment by skrosoft** [comment]
Yes, canaksoy is right, with Swift I had to apply a clear color to the Menu View Controller's background ... but with objective-c it is not necessary, this is weird.
