### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by x2on** [romaonthego/RESideMenu#250]
Hi @romaonthego,

is this project still alive?
There are many PR's that are currently not merged.
If you need assistance please ask!

Best,

Felix

**Comment by irmakcan** [comment]
+1

**Comment by borut-t** [comment]
+1

**Comment by x2on** [comment]
So nearly 2 months without response - i think the project is not maintained anymore...

**Comment by matthewbordas** [comment]
Have you guys tried to email him?

romefimov@gmail.com

**Comment by Tedko** [comment]
I asked him on twitter

**Comment by alibasta** [comment]
+1

**Comment by dasilvans** [comment]
the project is not maintained anymore?
