### ISSUE TITLE
I have trouble.

### ISSUE THREAD

**Issue by ArmyXomuiL** [romaonthego/RESideMenu#284]
<img width="326" alt="screenshot at 08 12-21-34" src="https://cloud.githubusercontent.com/assets/8521655/14379781/d69ae0b4-fd8c-11e5-8267-436611cc9942.png">

I am hide UITabBarController and get this trouble. All good if I do not use RESideMenu.

**Comment by lveecode** [comment]
@ArmyXomuiL Looks like the problem is with the automaticallyAdjustsScrollViewInsets property, as it respects the parent view controller setting (and side menu controller is the parent controller in your case). 
Try setting automaticallyAdjustsScrollViewInsets = NO on the side menu controller.
