### ISSUE TITLE
Open specific view when remote push notification appear in device 

### ISSUE THREAD

**Issue by AhmAbdallah** [romaonthego/RESideMenu#294]
how to open specific view in case of app closed, foreground, and background.
I used code on simple example but its not appear my view only black view.
Plz help!!!

**Comment by middiu** [comment]
seems like this is repo is not maintained anymore... is anyone still maintaining a fork of it?

**Comment by AhmAbdallah** [comment]
I solved it and I used this solution in case of app use push notification:-
//----------------------------
    UIStoryboard *storyboard=[UIStoryboard storyboardWithName:@"Main" bundle:[NSBundle mainBundle]];
    UIViewController *detailVC= (AAMedicalLibararyByIDViewController *) [storyboard instantiateViewControllerWithIdentifier:@"AAMedicalLibararyByIDViewController"];
RESideMenu *sideMenu = (RESideMenu *)self.window.rootViewController;
[((UINavigationController *)sideMenu.contentViewController) pushViewController:detailVC animated:YES]; 
//----------------------------
