### ISSUE TITLE
Can't use pan gesture if I Push a new controller

### ISSUE THREAD

**Issue by nipun0505** [romaonthego/RESideMenu#306]
This is my initialization code:

`RESideMenu mySideMenu = [[RESideMenu alloc] initWithContentViewController:_mainNavigationController leftMenuViewController:_leftSidebarController rightMenuViewController:nil];`

Here `_mainNavigationController` is a navigation controller. If I push an new controller, I loose the pan gesture all together. Is this the expected behavior?

**Comment by PengSiSi** [comment]
if you solved，Please tell me the solution，thank you.

**Comment by nipun0505** [comment]
@PengSiSi Just set the `interactivePopGestureRecognizer.enabled` to FALSE for your navigation controller as well as the `interactivePopGestureRecognizerEnabled` to FALSE for `RESideMEnu` object

**Comment by PengSiSi** [comment]
I think  not this problem, I just push to one page will not be able to click on the button.

**Comment by nipun0505** [comment]
@PengSiSi Sorry, I didn't get it
