### ISSUE TITLE
AppearanceTransition event for menu and contents

### ISSUE THREAD

**Issue by ichina** [romaonthego/RESideMenu#42]
Ромыч, твой фреймворк охуеннен, я прям сразу себе воткнул его, ток сделай, пжалки, всякие     [self.contentViewController beginAppearanceTransition:YES animated:animated]; и всякие прочие понты
 для меню, чтоб в контроллере меню выстреливали ивенты типа viewDidAppear,viewDidDissappear, ну ты понял, а то ща они выстреливают один раз при первом появлении. Заранее спасибо))

**Comment by kundan122** [comment]
please use english
