### ISSUE TITLE
How to integrate a tutorial screen into the RESideMenu?

### ISSUE THREAD

**Issue by goelv** [romaonthego/RESideMenu#58]
Hi Roman,

I am using RESideMenu in my project and I want to incorporate a tutorial screen for the  user.

This is what I want to do:
1) the first time the app loads, direct the user to the tutorial screen.
2) in future app launches, the app should load to the one of my other view controllers but give the option to the user to go back to the tutorial screen. 

For simplicity sake, consider the tutorial screen to be another view controller which will be part of the RESideMenu 'menu view controller'. 

Is there a way to do this? 
thanks,
Varun

**Comment by kuldeept92** [comment]
how to dynamic change content of side menu. .. ? please help us fast .
